=== Eygodon/Cours/L2/web/Site Projet/Projet-Web/Projet-Web-master/SITE_real/XML/pewdiepie.dtd
<!ELEMENT pewdiepie (video+)>
<!ATTLIST pewdiepie
        user ID #REQUIRED>

<!ELEMENT video (thumbnail,title,length,date,views,ratio,mark?)>
<!ATTLIST video
        number CDATA #REQUIRED
        type (MemeReview|LWIAY|YLYL|VR Chat|Tik Tok|none|#PCDATA) #REQUIRED>

<!ELEMENT thumbnail (img)>
<!ATTLIST thumbnail
        id ID #IMPLIED>

<!ELEMENT title (#PCDATA)>
<!ATTLIST title
        id ID #IMPLIED>

<!ELEMENT length (#PCDATA)>
<!ATTLIST lenght
        id ID #IMPLIED>

<!ELEMENT date (#PCDATA)>
<!ATTLIST date
        id ID #IMPLIED>

<!ELEMENT views (#PCDATA)>
<!ATTLIST views
        id ID #IMPLIED>

<!ELEMENT ratio (#PCDATA)>
<!ATTLIST ratio
        id ID #IMPLIED>

<!ELEMENT mark (#PCDATA)>
<!ATTLIST mark
        id ID #IMPLIED>

<!ELEMENT img EMPTY>
<!ATTLIST img
        src CDATA #REQUIRED
        alt CDATA #REQUIRED>

=== Eygodon/Cours/L2/web/Site Projet/Projet-Web/Projet-Web-master/SITE_real/XML/pewdiepie.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE pewdiepie SYSTEM "pewdiepie.dtd">
<pewdiepie user="t-series">

<video type="MemeReview" number="44">
    <thumbnail>
        <img src="https://i.kym-cdn.com/entries/icons/original/000/026/128/maxresdefault_(1).jpg" alt="memereview44"/>
    </thumbnail>
    <title>DVD screensaver hits corner?!!![MEME REVIEW]👏👏#44</title>
    <length>15:17</length>
    <date>06/12/2018</date>
    <views>6 657 182</views>
    <ratio>98.2</ratio>
    <mark id="deLouis">9.5/10</mark>
</video>
    

<video type="LWIAY" number="66">
    <thumbnail>
        <img src="https://vignette.wikia.nocookie.net/superepicfailpedia/images/3/30/LWIAY_logo.jpg/revision/latest?cb=20180420191614" alt="lwiay66"/>
    </thumbnail>
    <title>We broke a world record! LWIAY - #0061</title>
    <length>15:15</length>
    <date>30/12/2018</date>
    <views>14 575 053</views>
    <ratio>98.7</ratio>
    <mark id="deYann">10/10</mark>
</video>

<video type="YLYL" number="41">
    <thumbnail>
        <img src="https://i.ytimg.com/vi/kbDs-YG0y7Q/maxresdefault.jpg" alt="ylyl41"/>
    </thumbnail>
    <title>YOU LAUGH YOU LOSE ***Stale Memes*** YLYL #0041</title>
    <length>11:03</length>
    <date>12/10/2018</date>
    <views>6 533 749</views>
    <ratio>97.9</ratio>
</video>
</pewdiepie>
